import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { FirebaseProvider } from "@/context/FirebaseProvider";
import { ModalProvider } from "@/context/ModalContext";
import { FontSizeProvider } from "@/context/FontSizeContext";
import LoginModal from "@/components/LoginModal";
import Sidebar from "@/components/Sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <FirebaseProvider>
          <AuthProvider>
            <ModalProvider>
              <FontSizeProvider>
                <div className="layout-container">
                  <Sidebar />
                  <main className="layout-main-content">
                    {children}
                  </main>
                </div>
                <LoginModal />
              </FontSizeProvider>
            </ModalProvider>
          </AuthProvider>
        </FirebaseProvider>
      </body>
    </html>
  );
}
